// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasklVDTKxLXk5DtCj0O_FUXhZckaK9Xs',
    appId: '1:572876146204:web:4fbd8488bce27fd19301d9',
    messagingSenderId: '572876146204',
    projectId: 'tiktokclone-dbseotjs',
    authDomain: 'tiktokclone-dbseotjs.firebaseapp.com',
    storageBucket: 'tiktokclone-dbseotjs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANNM89Qw63OwYwEv1hq3Vb0lnlXujgzSU',
    appId: '1:572876146204:android:a676cea475700be49301d9',
    messagingSenderId: '572876146204',
    projectId: 'tiktokclone-dbseotjs',
    storageBucket: 'tiktokclone-dbseotjs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCoN7mFO8Wgb77ULCZpPD0TM2eZeqSHw',
    appId: '1:572876146204:ios:0c2a175169be8ed29301d9',
    messagingSenderId: '572876146204',
    projectId: 'tiktokclone-dbseotjs',
    storageBucket: 'tiktokclone-dbseotjs.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasklVDTKxLXk5DtCj0O_FUXhZckaK9Xs',
    appId: '1:572876146204:web:65ef50c27ba6f15f9301d9',
    messagingSenderId: '572876146204',
    projectId: 'tiktokclone-dbseotjs',
    authDomain: 'tiktokclone-dbseotjs.firebaseapp.com',
    storageBucket: 'tiktokclone-dbseotjs.appspot.com',
  );
}